import { rxova } from "@rxova/repo-config/eslint";

export default rxova({
  tsconfigRootDir: import.meta.dirname,
  // The libraries run in browsers, tabs and workers as well as on Node.
  node: true,
  browser: true,
  tests: true,
  // React hooks rules on the hooks and the demo; `useEverywhere`-style effects
  // are plain `useEffect`s, so no `additionalHooks`.
  react: { files: ["**/*.tsx", "apps/demo/src/**"] },
  ignores: [
    // Generated by TypeDoc at build time.
    "apps/docs/src/content/docs/api/",
    // Both generated by apps/demo/build-fixtures.mjs at dev/test time.
    "apps/demo/public/mfe/",
    "apps/demo/public/relay/",
    // Generated by apps/docs/scripts/build-playground.mjs.
    "apps/docs/public/playground/",
    "prototypes/",
  ],
  // Scripts and CLIs print to stdout; `enableDebug` and the bus-observer guard
  // in core's debug.ts exist to write to the console.
  consoleAllowed: [
    "scripts/**",
    "**/scripts/**",
    "packages/benchmarks/**",
    "packages/codemod/src/cli.ts",
    "packages/core/src/debug.ts",
  ],
  rules: {
    "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
    "@typescript-eslint/consistent-type-imports": ["error", { fixStyle: "inline-type-imports" }],
    // The demo and showcase are prose-heavy pages written in JSX. React renders an
    // apostrophe in text as-is, and `&apos;` everywhere would only obscure the copy.
    "react/no-unescaped-entities": "off",
  },
});
